#!/bin/bash


# modified commands
#alias diff='colordiff'              # requires colordiff package
alias grep='grep --color=auto'
alias more='less'
alias df='df -h'
alias du='du -c -h'
alias mkdir='mkdir -p -v'
alias nano='nano -w'
alias ping='ping -c 5'
#alias ..='cd ..'

# new commands
#alias da='date "+%A, %B %d, %Y [%T]"'
#alias du1='du --max-depth=1'
alias hist='history | grep $1'
#alias openports='netstat --all --numeric --programs --inet'
#alias pg='ps -Af | grep $1'         # requires an argument (note: /usr/bin/pg is installed by the util-linux package; maybe a different alias name should be used)

# privileged access
if [ $UID -ne 0 ]; then
    alias sudo='sudo '
    alias scat='sudo cat'
    alias svim='sudo vim'
    alias root='sudo su'
    alias reboot='sudo reboot'
    alias shutdown='sudo shutdown -h now'
    alias halt='sudo halt'
    alias update='sudo pacman -Su'
    alias netcfg='sudo netcfg2'
    alias hibernate='sudo pm-hibernate'
    alias suspend='sudo pm-suspend'
fi

# ls
alias ls='ls -hF --color=always'
alias lr='ls -R'                    # recursive ls
alias ll='ls -l'
alias la='ll -A'
alias lx='ll -BX'                   # sort by extension
alias lz='ll -rS'                   # sort by size
alias lt='ll -rt'                   # sort by date
alias lm='la | more'

# safety features
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -I'                    # 'rm -i' prompts for every file
alias ln='ln -i'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# tab completion
complete -cf sudo # autocomplete i bash ved brug af sudo
complete -cf man
complete -W "$(echo `cat ~/.ssh/known_hosts | cut -f 1 -d ' ' | sed -e s/,.*//g | uniq | grep -v "\["`;)" ssh

# If a package in the list is already installed on the system, it will be reinstalled even if it is already up-to-date, unless you use the --needed option.
alias install='sudo pacman-color -S --needed'
alias installed='pacman-color -Qqs'
alias pacman='sudo pacman-color' # kræver pacman-color pakken
alias clean='sudo pacman-color -Scc'
alias cleandeps='sudo pacman-color -Rns $(sudo pacman-color -Qdtq)'
alias info='pacman-color -Si'
alias upgrade='yaourt -Syu --aur'
alias matlab='matlab -desktop'

alias dtumnt='bash /home/paw/.scripts/dtumnt.sh'
alias dtuumnt='fusermount -u ~/dtumnt'

# Emacs, # hvis emacs --daemon ikke kører, bruges nano i stedet
alias et='emacsclient -t -a nano'
alias ef='emacsclient -c -a nano'
alias kill_emacs='emacsclient --eval "(progn (save-some-buffers t t) (kill-emacs))"'
# edit file with root privs
alias efs="SUDO_EDITOR=\"emacsclient -c -a emacs\" sudoedit"
alias ets="SUDO_EDITOR=\"emacsclient -t -a emacs\" sudoedit"
